# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Chapter01Sample03' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chapter01Sample03
  pod 'AudioExtension', :path => '../AudioExtension'

end
